# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# Twilio

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 56a8d848b4809c9b8aac74f5eb3183a09b936731873b28a2305c55170df5607416d9abe7659ad1d9f8bf1c067e7aa5b40812d32060b6c04d64dc0e0238685acb
  twilio_account_sid:  <%= ENV.fetch("SECRET_KEY_BASE", "ACfd8549c52e1a19b81d4dadaa13fab195") %>
  twilio_auth_token:  <%= ENV.fetch("SECRET_KEY_BASE", "1cbb23870635559bc283f0b1e328a49b") %>
  twilio_phone_number:  <%= ENV.fetch("SECRET_KEY_BASE", "12069666651") %>

test:
  secret_key_base: bc2a1f141d16b3e54e5a1504920e0e4239aea129ff3d86eea65150000bc492d0acd2abaf05315363cc31cc6d3ded083cdf1e1b934e573e2eb2b390684c5befc4



# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
